# Generated by Django 4.2.7 on 2023-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Django_Marketplace\\media/box.jpg', upload_to='./images/'),
        ),
    ]
