# Generated by Django 4.2.7 on 2023-11-25 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_message_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_chat', models.CharField(max_length=150)),
                ('creation_msg', models.DateTimeField(default=django.utils.timezone.now)),
                ('Principal_Chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.message')),
            ],
        ),
    ]
