# Generated by Django 4.2.7 on 2023-11-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0013_chat_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product_selling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product'),
        ),
        migrations.AlterField(
            model_name='message',
            name='transmitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmitter_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
